apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/miguel/.minikube/ca.crt
    server: https://192.168.64.5:8443
  name: minikube
- cluster:
    certificate-authority-data: YmxlaAo=
    server: https://ad.eks.com
  name: patata
- cluster:
    server: https://bleh.com/k8s/clusters/local
  name: rancher
contexts:
- context:
    cluster: patata
    namespace: custom-system
    user: patata
  name: patata
- context:
    cluster: minikube
    namespace: custom-system
    user: minikube
  name: minikube
- context:
    cluster: rancher
    namespace: custom-system
    user: user-mtp4h
  name: rancher
current-context: coolcluster
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/myuser/.minikube/client.crt
    client-key: /Users/myuser/.minikube/client.key
- name: patata
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - patata
      command: aws-iam-authenticator
      env: null
- name: user-mtp4h
  user:
    token: kubeconfig-user-mtp4h:YmxlaAo=
