apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop
- cluster:
    certificate-authority: /Users/miguel/.minikube/ca.crt
    server: https://192.168.64.5:8443
  name: belitre
contexts:
- context:
    cluster: docker-for-desktop
    user: docker-for-desktop
  name: docker-for-desktop
- context:
    cluster: belitre
    namespace: custom-system
    user: belitre
  name: belitre
current-context: "belitre"
kind: Config
preferences: {}
users:
- name: docker-for-desktop
  user:
    client-certificate-data: YmxlaAo=
    client-key-data: YmxlaAo=
- name: belitre
  user:
    client-certificate: /Users/myuser/.minikube/client.crt
    client-key: /Users/myuser/.minikube/client.key
