name: Build and test

on: [pull_request]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOLANG_VERSION: "1.19.5"
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: build and test
        run: make build-cross
