name: Build and test

on: [pull_request]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: build and test
        uses: ouzi-dev/go-make-action@v1.2.0
        with:
          target: 'build-cross'
      - name: Run go report card
        run: make score GITHUB_USER=github-actions GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} GITOPS_API_KEY=${{ secrets.GITOPS_API_KEY }} 